### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by AndrewGuenther** [CalPoly/thesis-template#4]
Tests should ensure that the template always compiles

**Comment by WardenGnaw** [comment]
Something like this? https://github.com/guillaumesalagnac/latex-compile/tree/master/test-cases

**Comment by AndrewGuenther** [comment]
Those test that the compiler works, I want to test that the template compiles when using a stable compiler.

**Comment by AndrewGuenther** [comment]
Something like this:
https://gist.github.com/snim2/9160862

That was Travis can run it on any incoming PRs as well

**Comment by coyotebush** [comment]
How about a Travis configuration that runs
```
latexmk -pdf -f -interaction=nonstopmode main.tex
```
? This will print all the errors and exit non-zero if there are any.

Perhaps it would be useful to also have a little bit of content in this repository, although it's not at all clear where to draw the line. For instance, https://github.com/CalPoly/thesis-template/pull/3/commits/71ac5c96ad248491617354feea45b25c473bd969 resolves a problem with a specific yet typical thesis structure.

**Comment by AndrewGuenther** [comment]
@coyotebush Do you know what packages need to be installed for everything to compile? I've added the usual suspects, but it still won't compile for me. (but works in ShareLaTeX)

**Comment by coyotebush** [comment]
Is it failing at a `\usepackage`? Which one?

I have all of these Debian packages installed and they're (more than) sufficient to compile it.
```sh
> aptitude search -F '%p' '~i texlive !doc'
texlive-base
texlive-bibtex-extra
texlive-binaries
texlive-extra-utils
texlive-font-utils
texlive-fonts-extra
texlive-fonts-recommended
texlive-generic-recommended
texlive-latex-base
texlive-latex-extra
texlive-latex-recommended
texlive-pictures
texlive-pstricks
texlive-publishers
texlive-science

**Comment by AndrewGuenther** [comment]
I'll add those to the Travis script and see how it goes

**Comment by AndrewGuenther** [comment]
@coyotebush Here's the build after installing those packages, looks like we're still missing something. Same error as the last run.

https://travis-ci.org/CalPoly/thesis-template/builds/134949359

**Comment by coyotebush** [comment]
I see, the default Travis environment is Ubuntu 12.04, which has an ancient version of TeX Live. I'd be comfortable just [targeting 14.04](https://docs.travis-ci.com/user/trusty-ci-environment/), since students are unlikely to be running a four-year-old release by now. (Although there might be an argument for supporting CentOS 6 on the CSC department lab systems, which has the same issue with the morefloats package.)

Also: `-interaction=nonstopmode` would make the compiler try to continue after an error, instead of hang waiting for input until Travis kills it.

**Comment by AndrewGuenther** [comment]
I was getting an error when passing the `-interaction` flag, but that is likely also due to the ancient package versions. I'll try again tonight.

**Comment by AndrewGuenther** [comment]
Resolved
