### ISSUE TITLE
Appendices in all caps must be at the top of the appendix section

### ISSUE THREAD

**Issue by Jdban** [CalPoly/thesis-template#5]
They are telling me that APPENDICES must be centered in all caps at the top of the first appendix page such as with the Bibliography section seen here: http://i.imgur.com/1T0BXTD.png

Quote from grad dept: "Please insert "Appendices" in all CAPS at the top of the page." (referring to the appendix)

I'm trying to get it working like they want, but currently it seems that the template does not do this (as far as I can tell).

**Comment by coyotebush** [comment]
That sounds weird and awkward to me, but I think we can make it happen.

**Comment by Jdban** [comment]
Yeah, it sounds weird to me too. I tried fiddling with the LaTeX, but couldn't make it happen.

I found a thesis here that does what they want as an example (APPENDICES sample is on page \#116): http://digitalcommons.calpoly.edu/theses/1549/

**Comment by coyotebush** [comment]
That's an interesting example because it doesn't have an "Appendix A" heading, so instead it's the "APPENDICES" header that corresponds to the other chapter headings.
